### ISSUE TITLE
Move to CMake

### ISSUE THREAD

**Issue by solodon4** [solodon4/Mach7#22]
Maintaining Visual C++, XCode etc. projects has became too cumbersome. Move to CMake

**Comment by kirbyfan64** [comment]
Ever thought of using Bakefile? It's kind of like CMake, but it generates build files that can be checked in to version control. That way, the project users don't see a difference.

**Comment by solodon4** [comment]
Never tried actually, but would definitely be curious to give it a try. How difficult is it to set up for multiple targets with individual one-file test cases as opposed to projects with multiple files? Current Makefile tries to grab everything in the folder and build those with same settings, which is maintainable enough to not have to worry when new test cases are added. Can you provide/contribute an example of something like this on some of the tests here?

P.S. Btw, thanks a lot for reediting the project - it's gotten 6 times more exposure from your post than it got from a year residing on github, with prior publications and talks at C++ conferences! Work is overrated, i just need to know the right redditors ;-)

**Comment by kirbyfan64** [comment]
> How difficult is it to set up for multiple targets with individual one-file test cases as opposed to projects with multiple files?

You still have to write them explicitly, but it's pretty darn easy thanks to templates.

> Can you provide/contribute an example of something like this on some of the tests here?

Sure! Just give me a few hours; I'm on a phone right now.

> P.S. Btw, thanks a lot for reediting the project - it's gotten 6 times more exposure from your post than it got from a year residing on github, with prior publications and talks at C++ conferences!

No prob. :)

**Comment by kirbyfan64** [comment]
@solodon4 Oh my gosh, I completely forgot about this! So sorry! Would you still be interested in using Bakefile?

Again, *so* sorry.

**Comment by solodon4** [comment]
No problem. Sure, just create a pull request when you have the definitions ready. You might want to wait though as I broke the build while moving headers this week, need to fix it first.
