### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by GuapoTaco** [solodon4/Mach7#25]
It seems that any link I click on, it turns out to really not work. I just go to the github 404 page, which leads me to believe that the resources are private to the repo editors, and not me (or the open public)

One good example is here:

Fibonacci numbers demonstrates the use of patterns with built-in types in Mach7:

the link embedded in that (https://github.com/solodon4/Mach7/blob/master/code/numbers.cpp#L202-L216) gives me the 404.

**Comment by solodon4** [comment]
Thank you! Fixed it. The problem was because after moving files to a subdirectory in issue #18 I forgot to update the links.
