### ISSUE TITLE
Are there any example of a recursive match?

### ISSUE THREAD

**Issue by lolisa** [solodon4/Mach7#26]
For example, if you have a n : nat (the classical ADT), how can you do match "n with S (S n') ..."?
Are there limitation in the current implementation of recursive match?
Thank you.

**Comment by solodon4** [comment]
The 3rd case in lambda example is a recursive match: https://github.com/solodon4/Mach7/blob/master/code/test/time/lambda.cpp#L97-L114
If you have a specific functional example in mind, I can translate it for you into a working Mach7 example. Just post your example here

**Comment by lolisa** [comment]
Thx, I will migrate! :smile:

**Comment by solodon4** [comment]
Feel free to ask questions.
