### ISSUE TITLE
what do you recommend for runtime pattern matching?

### ISSUE THREAD

**Issue by autosquid** [solodon4/Mach7#27]
what do you recommend for runtime pattern matching?

**Comment by solodon4** [comment]
Can you elaborate what do you mean by that? The pattern matching done by this library happens at run-time against run-time values. For example, you can match for derived classes where only base class is known statically at compile-time, the library would perform a very efficient run-time check, on par with performance of the visitor-design pattern. You can match strings against a set of regular expression patterns or given values, you can also create your own patterns which can be used with the rest of the library to perform specific run-time checks.

**Comment by autosquid** [comment]
I came with the wrong question. Now I am closign it.
