### ISSUE TITLE
unit test exp.cpp triggers an UB

### ISSUE THREAD

**Issue by akrzemi1** [solodon4/Mach7#40]
Unit test `exp.cpp` has an undefined behavior and triggers a crash when I run tests.

In line 375 an object of type `Mod` is created and then passed to function `myeval`. Function `myeval` does not have a case for type `Mod` so it exits w/o any return statement.

I cannot fix it as I do not know what this unit test is intended to illustrate.

**Comment by solodon4** [comment]
Commit 3f5310c now makes XTL_UNREACHABLE to actually assert to catch these kind of cases.
