### ISSUE TITLE
problems building unit tests with make

### ISSUE THREAD

**Issue by akrzemi1** [solodon4/Mach7#41]
I can't build and execute unit tests on Red Hat Linux using make.

Top-level Makefile contains like:

```make
# Create a list of source files.
SOURCES  = $(shell ls *.cpp)
```

But `ls *.cpp` is not a valid bash command, and I get an error.  You probably meant either `find -name *.cpp` or `find -maxdepth 1 -name *.cpp`, but I do not know which one.

If I fix this, and then run `make test`, I get a bash error:

```
basename: extra operand `comp.clang.hpp'
Try `basename --help' for more information.
======================================== [ *.exe ]
/bin/sh: line 17: ./*.exe: No such file or directory
```

**Comment by solodon4** [comment]
Not sure why this happens as _ls_ is a basic shell command. What is your default shell on that machine? It builds successfully on other flavors of Linux (see https://travis-ci.org/solodon4/Mach7) so my guess is the shell difference. 

In any case you should still be able to build a particular file by replacing it's extension with .exe: e.g.: make example05.exe. I kept .exe even though it doesn't mean anything on unix-based systems to simplify maintenance of relevant scripts on windows and unix-like systems.

**Comment by akrzemi1** [comment]
I am using bash, 4.1.2 on RedHat:
```
bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The problem is not with having or not having `ls`, but with the glob pattern:

```
$ ls *.cpp
ls *.cpp
ls: cannot access *.cpp: No such file or directory
```

**Comment by solodon4** [comment]
Not sure I understand the problem then. The top level Makefile, however, simply passes the control to the makefiles in test/unit and test/time - by itself it doesn't (shouldn't) try to build files in the root since there aren't any. The reason that ls statement is there however is to keep all the Makefiles in different subfolders more or less the same so that I can easily compare them in diff tool when I make changes and replicate corresponding changes in all of them.

**Comment by akrzemi1** [comment]
Oh, now I realize. There is nothing wrong with `ls *.cpp` -- it is just that when I call it from directory that contains no `.cpp` file, I get a diagnostic message (I expected I would get a 0-sized file list). Sorry to have confused you.

But I still need one explanation. How do you imagine I will be building with `makefile` (suppose I cannot use `cmake`). Am I supposed to first go into `code/test/unit` and call `make` and `make test` there; then go to `code/test/time` and call `make` and `make test` again?

**Comment by solodon4** [comment]
I build by just invoking make in the code directory - it calls make in test/unit and test/time from there. This is also how the build with Travis is configured right now, both on Linux and OSX. If I need to only build a specific file, I simply do make example05.exe to build example05.cpp
