### ISSUE TITLE
Linker errors when building unit tests

### ISSUE THREAD

**Issue by kirbyfan64** [solodon4/Mach7#44]
This occurs with both CMake and the Bakefile system I'm working on:

```
[6/172] Linking CXX executable unit/example01
FAILED: : && /home/ryan/stuff/Downloads/clang+llvm-3.6.0-x86_64-linux-gnu/bin/clang++   -fcolor-diagnostics   unit/CMakeFiles/example01.dir/example01.cpp.o  -o unit/example01  -rdynamic && :
unit/CMakeFiles/example01.dir/example01.cpp.o: In function `mch::vtblmap<mch::type_switch_info>::get(void const*)':
../unit/example01.cpp:(.text._ZN3mch7vtblmapINS_16type_switch_infoEE3getEPKv[_ZN3mch7vtblmapINS_16type_switch_infoEE3getEPKv]+0xd3): undefined reference to `mch::vtblmap<mch::type_switch_info>::update(long)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This happens when linking pretty much any of the tests.

**Comment by solodon4** [comment]
Yes, that's one of the breaks from the change in include directories I did on Andrzej's request this week. I'll fix these up during the weekend and ping you back.

**Comment by solodon4** [comment]
What OS are you on and what compiler/linker versions are you using? On my Mac OS X Yosemite 10.10.5 with CMake 3.5.0 everything builds without issues both with clang and with g++:
cd test
mkdir build-clang
cd build-clang
/Applications/CMake.app/Contents/bin/cmake ..
/Applications/CMake.app/Contents/bin/cmake --build .
cd ..
mkdir build-gcc
cd build-gcc
CC=/usr/local/bin/gcc-4.8 CXX=/usr/local/bin/g++-4.8 /Applications/CMake.app/Contents/bin/cmake -G "Unix Makefiles" ..
/Applications/CMake.app/Contents/bin/cmake --build .
cd ..

**Comment by kirbyfan64** [comment]
@solodon4 I'm on Ubuntu 14.04 with Clang 3.6. Interestingly, it works with GCC, but NOT Clang...

**Comment by solodon4** [comment]
I'll try tomorrow on an Ubuntu VM

**Comment by solodon4** [comment]
This seems to be caused by __builtin_assume in Clang, so I commented out its use for the moment. This is tracked by issue #55 . I was able to successfully build with Clang on Linux on Travis CI VMs, so I was wondering if you can sync up to the tip and check if the issue still repros. Thank you!

**Comment by kirbyfan64** [comment]
@solodon4 Yup, it works now!
