### ISSUE TITLE
support mail address not valid

### ISSUE THREAD

**Issue by forflo** [solodon4/Mach7#59]
Hello Yuriy,

I was trying to send you an email, but the
mail address in section *support* doesn't seem to
be valid. Could you check that?

Best regards
Florian

**Comment by solodon4** [comment]
Hi Florian,

The address yuriy.solodkyy+mach7support@gmail.com is correct. Gmail has this feature where you can put anything after a + and it will still arrive to your mailbox (https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html). It is useful when you have to put email address out or give it to external company as you can later filter based on full email or delete everything with it once email was leaked and you get too much spam. The only problem I can see if the email client you are using wouldn't allow + in the email.

**Comment by forflo** [comment]
The problem is obviously my browser. Cromium doesn't include the "+". Insead, it replaces it with a single space. Sorry, for that!
