### ISSUE TITLE
No compile time complaint where there should be one

### ISSUE THREAD

**Issue by forflo** [solodon4/Mach7#60]
Hi Yuriy,

I played around with `compile-lambda-a.cpp` and added a new function whose
purpose is to replace every string in any lambda term with "foobar". This makes use of
a nested `Match {...} EndMatch` construct. The full version of this file is available at a [gist](https://gist.github.com/forflo/775f14fed757a3c20d19a37c235bb72f#file-case_test_01-cpp-L69) that I uploaded.

The relevant parts are given here:

```c++
void change_vars(Term& t) {
    var<Var&>  v;
    var<Term&> t1, t2;
    var<std::string> s;

    Match(t)
    {
        Case(C<Var>(s)) { return; }
        Case(C<Abs>(&v,&t1)) {
            ((Var &) v).name = std::string("foobar");

            // "Match(t1) {" instead of the line below
            // produces a SIGSEGV. Why is that?
            Match((Term &) t1){
                Case(C<Var>(v)) {
                    ((Var &) v).name = std::string("foobar");
                    return;
                }
                Otherwise() { return; }
            } EndMatch

            change_vars(t1);
            return ;
        }
        Case(C<App>(&t1,&t2)) {
            change_vars(t1);
            change_vars(t2);
            return ;
        }
    }
    EndMatch

    return;
}
```

I know by now, that the instanciation of the `var` template produces `structs` with appropriately overloaded conversion operators. But in the context of the `Match` statement unambiguous type deduction should not be working and thus the compiler should produce an error when it encountered `Match(t1){` (see comment in above code block). But that does not happen.

With `Match(t1)` instead of the correct `Match((Term &) t1)` the [code](https://gist.github.com/forflo/775f14fed757a3c20d19a37c235bb72f) compiles, but quickly produces a SIGSEGV. Why does it even compile?

Best regards
Florian

**Comment by forflo** [comment]
##### Additional Information (i forgot to add)

Version of GNU g++: `g++ (GCC) 6.1.1 20160501`
Linux Kernelversion: `4.5.4-1-ARCH`

**Comment by solodon4** [comment]
This is certainly a bug: i see segfault both in g++ and in clang when building from command line (even though when building with clang from Xcode it works) and it fails to compile in Visual C++. I'll try to fix this in the coming days.

To answer your question: ideally the code should compile. While `var<T>` is a pattern in the LHS, we expect to be able to use its bound value in the RHS. For this reason `var<T>` tries to imitate a value of type T as close as C++ allows today. In Match(t1), t1 is used in RHS and thus ideally should behave as a value, not as a pattern. I almost certainly know why it segfaults, I'll just have to look into why the library failed to get to the underlying value.

**Comment by solodon4** [comment]
While i'm looking into this, here is a suggestion for you to avoid nested matches altogether. Your outer Match statement can be rewritten as following using nested patterns:

```C++
    Match(t)
    {
        Case(C<Var>(s)) { return; }
        Case(C<Abs>(&v,C<Var>(v))) { ((Var &) v).name = std::string("foobar"); return; }
        Case(C<Abs>(&v,&t1)) {
            ((Var &) v).name = std::string("foobar");
            change_vars(t1);
            return ;
        }
        Case(C<App>(&t1,&t2)) {
            change_vars(t1);
            change_vars(t2);
            return ;
        }
    }
    EndMatch
```

Note how the second case clause now effective does the same check for you via a nested pattern. It is important that it precedes the 3rd clause (as oppose to follows it) because the check for term will succeed on Var (i.e. 3rd clause is more general and everything that matches 2nd clause will match the 3rd one in this example). The same nested pattern is used in the 3rd Clause of the [lambda calculator example](https://github.com/solodon4/Mach7/blob/master/code/test/time/lambda.cpp#L101-L118) shown on the front page of the project. There it is used to detect App applied to Abs in the first argument.

**Comment by solodon4** [comment]
Note also that you don't have to bind everything by reference when you already have pointers in your data-structure - you can use pointers and save yourself from having to apply address combinator & in the LHS. For examples of what I am talking about, please have a look at [cppcon-matching.cpp](https://github.com/solodon4/Mach7/blob/master/code/test/unit/cppcon-matching.cpp), which is close to the code you are trying to build. More details about that file can be found in my CppCon 2014 presentation: [slides](http://bit.ly/AcceptNoVisitors), [video](http://bit.ly/AcceptNoVisitorsVideo). It uses slightly older experimental header mach7/type_switchN-patterns.hpp, but you should be able to replace it with the most recent one mach7/type_switchN-patterns-xtl.hpp with no changes to code. Please let me know if it doesn't work.

**Comment by forflo** [comment]
> While i'm looking into this, here is a suggestion for you to avoid nested matches
> altogether. Your outer Match statement can be rewritten as following using nested patterns:

It's a neat workaround, I have to admit. Though, I find nested `Match` statements to be much more readable than tightly packed nested Patterns.

> For examples of what I am talking about, please have a look at cppcon-matching.cpp, which
> [...]
> Please let me know if it doesn't work.

Perfect. Yes I'll do that, thanks!

**Comment by solodon4** [comment]
That was not intended as workaround, - nested patterns are a canonical feature of pattern matching that make it extremely expressive and powerful. They were in fact described in the original 1969 paper that gave rise to pattern matching as we know it today in all the functional languages. The programmer just describes the cases explaining the structural properties he is interested in and the job of a compiler is to generate the most efficient decision tree without duplicate checks or backtracking that implements that case analysis. 

One of the most famous uses of nested patterns is balancing of red-black trees, which in functional languages like O'Caml can be expressed in just about [4 lines of code](http://rosettacode.org/wiki/Pattern_matching#OCaml) (see function balance). Same functionality in procedural languages like C or C++ usually takes about 6 pages of very obscure code, that doesn't really show what are we trying to achieve. In the above O'Caml code you explicitly see in each line what case are we looking at and how do we perform rotation for that case. Mach7 library was started explicitly to be able to do this kind of nested checks expressively and efficiently, so it is definitely not an accident that it can do it. Here is [how red-black tree balancing looks like in Mach7](https://github.com/solodon4/Mach7/blob/master/code/msvc/RedBlackTree/red-black-tree.cpp#L172-L180).

**Comment by solodon4** [comment]
Can you try building the program when it ICEs with lower optimization level? When I build with -O1 instead of -O2 inside Clang, the problem seems to go away.

**Comment by forflo** [comment]
> That was not intended as workaround

Sorry, my bad. `Workaround` was definitely the false term for that. `Alternative` would've been the better choice.

> One of the most famous uses of nested patterns is balancing of red-black trees, which in functional languages like O'Caml can be expressed in just about 4 lines of code (see function balance) 

Yes, I already looked at that.

> Can you try building the program when it ICEs with lower optimization level? When I build with -O1 instead of -O2 inside Clang, the problem seems to go away.

Ok, here my results:
 
| Compiler flags | Compiler | Compiler result |
|:-:|:-:|:-:|:-:|
| -Wall -Wextra -pedantic -time -O0 -s -DNDEBUG -DXTL_MESSAGE_ENABLED=0 -std=c++0x | g++ | SIGSEGV |
| -O1 [... same as above ...]  | g++ | Program halts but does not exit |
| -O2 [... same as above ...]  | g++ | SIGSEGV |
| -O0 [... same as above ...]  | clang++ | works as expected |
| -O1 [... same as above ...]  | clang++ | works as expected |
| -O2 [... same as above ...]  | clang++ | SIGSEGV |

**Comment by forflo** [comment]
By the way: For further testing, you can rely on me using the already existing Makefile in `code/test/compile-time/`.

**Comment by solodon4** [comment]
I wouldn't use anything from test/compile-time if I were you. The tests there are mostly snapshots of other tests frozen back in time that I used to time the compilation times reported in the paper. Those tests, unlike the regular tests in test/unit and tests/time are not updated. You should be able to build everything with Makefile in test/time and test/unit as well as the Makefiles are all the same to the extent they can be. If you put a source file in any of these folders, say `mytest.cpp`, you can build just that file by invoking `make mytest.exe` (even on Linux and Mac, I know it's not orthodox to have .exe on those, but it simplifies maintenance of the build scripts for me). To compile with a different compiler, you can use: `make CXX=clang mytest.exe`

**Comment by solodon4** [comment]
Hi Florian,

Can you please check that the above check-in fixed this issue on your side as well?

Thank you!
Yuriy

**Comment by forflo** [comment]
Hey Yuriy,

It works on my side as well.
Thank you too!

Florian
