### ISSUE TITLE
Compile time performance

### ISSUE THREAD

**Issue by Rupsbant** [solodon4/Mach7#63]
A very subjective question but:

Some templates take a long time to compile. Does this library introduce a great toll on compile times when used regularly? e.g. Is it possible to create exponential or quadratic compile times for simple patterns?

Don't know how to label this though. Sorry about that.

**Comment by Rupsbant** [comment]
Easy answer, see presentation
https://youtu.be/OkDS6hmU-w8?t=5000

Maybe you could expand on this in the README.

**Comment by solodon4** [comment]
While pattern composition relies on expression templates and type traits, the composition is straightforward top-down instantiation and the checks are independent of each other, so this never blows up exponentially. The control flow used by the efficient type switch underneath is laid out with macros and not with template meta-programs, so it doesn't have any overhead either.

This question was often asked before and we actually got some data on it. If you look at our GPCE'13 paper [Open Pattern Matching for C++](http://bit.ly/OPM-GPCE13), then you'll find in section 4.2 our discussion of compile-time overhead and comparison of our approach (Patterns as Expression Templates) against a typical alternative approach (Patterns as Objects). You can find the same data in the [slides](http://bit.ly/OPM13Slides) we used to present that paper (see slide 21). The overheads are negligible and comparable to non-template alternative approach.

This is a valid concern of course and I was aware of it while working on the library. In our previous work on [XTL](https://parasol.tamu.edu/xtl/) library for refining type systems we sometimes had type-checking algorithms of exponential complexity running as template meta-programs, which indeed blew up compilation times through the roof on most compilers (see Table 2 in section 4.4 of our [paper](https://parasol.tamu.edu/~yuriys/papers/XTL11.pdf) documenting the experience). We had parts of that library implemented 2 ways: use of SFINAE tricks and relying on overload resolution and the big lesson we've learned from that was that relying on overloading resolution was way easier to maintain and way easier for the compiler to digest. Mach7 was built with that in mind.
