### ISSUE TITLE
[maybe bug] Subtype Dynamic Cast failing inexplicably.

### ISSUE THREAD

**Issue by elfprince13** [solodon4/Mach7#77]
I have several different functions using Match/Case on the same type hierarchy, but which accept references to certain subgraphs of that hierarchy. I noticed that some Cases were not matching as expected, so I uncommented the debugging line in `subtype_dynamic_cast` from xtl.hpp.

My `stringify` function is being used to serialize ASTs, and accepts a reference to a `Node` (the root of the type DAG), since it needs to be able to handle any node and has a void return type. In this case, the debug print shows:
```
subtype_dynamic_cast<PKN4GPSM7PolygonE>(PKN4GPSM4NodeE) = 0x102813d00
```
When fed a Polygon.
However, matching on the same Polygon (in a context where the reference is to a Expr<Surface>, an intermediate type between Polygon and Node), I get:
```
subtype_dynamic_cast<PKN4GPSM7PolygonE>(PN4GPSM4ExprINS_7SurfaceENS_6AnyValEEE) = 0x0
```

Nonetheless, my own debug print of the `typeid()` shows `N4GPSM7PolygonE`.

**Comment by solodon4** [comment]
Hi Thomas,

Sorry for late reply - last 3 weeks have been very hectic for me. I was wondering if you can possibly create a small repro of your issue for me to have a closer look?

Thank you!

**Comment by elfprince13** [comment]
@solodon4 - I will see if I can come up with a m.w.e. The code in question is part of a closed source EDSL implementation, but we've open-sourced some of the techniques [here](https://github.com/Geopipe/Cxx-TEDSL), so hopefully I can port the offending segment over to a less sensitive code base.

**Comment by elfprince13** [comment]
After further debugging, it appears to be a false alarm. My FFI was passing in a derived pointer where a base pointer was expected. I remain baffled as to why typeid (and Xcode's lldb-based debugger) were able to compensate for this, but dynamic_cast was not; however *that* is an oddity in C++ itself, and not in Mach7.

My apologies for the confusion.
